version: '3.4'

services:
  app:
    build: .
    environment:
      - NODE_ENV=production
      - PROD_DB_STRING=${PROD_DB_STRING}
      - PROD_DB_USER=${PROD_DB_USER}
      - PROD_DB_PWD=${PROD_DB_PWD}
      - HOSTNAME=${HOSTNAME}
    ports:
      - 80:3000
      - 1001:1001
    volumes:
      - ./.env:/usr/src/app/.env
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    command: [--auth]
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
volumes:
  data:
